### ISSUE TITLE
Button on theme site aren't responsive on smaller screens

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoThemesSite#19]
The buttons (download, demo and homepage) aren't very responsive on smaller screens since they are overlapping other content. Here's a screenshot of the issue:

![](https://i.imgur.com/xgfZB5W.jpg)

**Comment by bep** [comment]
This looks fine in OSX (firefox + safari). Might be an Ubuntu issue?

**Comment by ghost** [comment]
Looks like this was fixed in #26 and can be closed @digitalcraftsman.
