### ISSUE TITLE
Themes seem to be missing

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoThemesSite#22]
I know some themes are blacklisted. But the current builds of the theme site only include themes whose name's first character is between a and h.

/cc @bep

**Comment by bitprophet** [comment]
Looks like this is the same issue as https://github.com/spf13/hugo/issues/1759:
- When I nag `hugoThemesSiteScript` and run `.generateThemeSite.sh`, I get:
  
  ```
  Building site for theme hugo-pacman-theme using its own exampleSite
  Example site for theme hugo-pacman-theme missing /static folder
  ```
  
  and serving the result is missing all themes from there on, as on the live site.
- Sure enough, https://github.com/spf13/hugoThemes/commit/183391ce82dbc3f8cc1f87b9ed97685fa9405837 was committed 3 days ago (which fits with my personal memory of the theme site showing all sites a ~week ago)
- I successfully patched the script as per that earlier issue, and my local instance now serves all expected themes: https://github.com/spf13/hugoThemeSiteScript/pull/11

**Comment by digitalcraftsman** [comment]
Thank you for the pull request.

**Comment by bep** [comment]
We have to fix the script.
