### ISSUE TITLE
themes.gohugo.io seems to be down

### ISSUE THREAD

**Issue by felipebueno** [gohugoio/hugoThemesSite#23]
Hi, @bep 👍 

themes.gohugo.io seems to be down

It doesn't throw any error but the page is blank.

<img width="1280" alt="screen shot 2016-06-04 at 15 52 47" src="https://cloud.githubusercontent.com/assets/241271/15801471/8ef2a398-2a6c-11e6-95bd-de3ba818cad1.png">

**Comment by bep** [comment]
Yes, it is up again now.

**Comment by felipebueno** [comment]
Thanks :smiley: 👍
