### ISSUE TITLE
Mobile menu hides when scrolling on mobile

### ISSUE THREAD

**Issue by anagio** [gohugoio/hugoThemesSite#25]
On mobile, when the mobile menu is open and you touch the screen and begin to scroll when you release your finger the `sidebar-menu` gets display none. The JS could use some attention and refactoring.

**Comment by bep** [comment]
I cannot reproduce this on my Android phone (5.1.1.), both Chrome and built-in browser works fine. 

What mobile gadget/browser do you experience this issue on?

I'm not a "master of frontend", so would love for others to chime in with a fix ...

**Comment by anagio** [comment]
Hi @bep i'm using a Samsung Galaxy s5 with Android version 6.0.1 and Chrome version 50.0.2661.89

I'd be happy to debug when I have additional time but wanted to submit an issue to see if anyone else is experiencing the same.

**Comment by digitalcraftsman** [comment]
I'm also not able to reproduce the issue with Android 5.1.1 and Chrome.

**Comment by onedrawingperday** [comment]
This belongs to the repo of the Hugo Theme https://github.com/gohugoio/gohugoioTheme/

Also there is an issue about the mobile menu which has other problems as well
Feel free to continue the discussion in https://github.com/gohugoio/gohugoioTheme/issues/141
