### ISSUE TITLE
Add twitter card tags

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoThemesSite#27]
So it looks prettier when shared. 

/cc @digitalcraftsman

**Comment by digitalcraftsman** [comment]
I've added the internal twitter cards template and the theme thumbnails to the frontmatter so hat they show up in a tweet. Once the theme site is rebuilt I'll test it.

**Comment by digitalcraftsman** [comment]
Currently, we use an inlined version of the twitter cards template instead of Hugo's internal template (see 7342957). Was this a temporary or persistent addition?

**Comment by bep** [comment]
I don't remember -- but I think I confused the symptom for something else ... In any way it was temporary. We added the missing field to the Hugo version.

**Comment by digitalcraftsman** [comment]
> In any way it was temporary. We added the missing field to the Hugo version.

In other words: your inlined template contained an additional field that wasn't present in Hugo's internal template back then?

**Comment by bep** [comment]
Yes.

**Comment by digitalcraftsman** [comment]
Hence we can move back to the internal template and remove the inlined version?

**Comment by bep** [comment]
Yes.
