### ISSUE TITLE
Suggestion: display available tags on the themes page

### ISSUE THREAD

**Issue by kaitlinnewson** [gohugoio/hugoThemesSite#28]
On the themes.gohugo.io page, it would be great to be able to see all of the available theme tags so that you can filter by the tags right from the landing page. The feature seems pretty hidden unless you know it's there!

**Comment by arikroc** [comment]
Couldn't agree more! https://github.com/spf13/hugoThemes/issues/248

"I wish there was a list at the top of the themes page with all the tags, and (counts) of num of themes with that tag, and then you could click to go to that page"

**Comment by arikroc** [comment]
Thanks, @bep! Looks great.
