### ISSUE TITLE
Polish theme site

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoThemesSite#3]
See shell script in:

https://github.com/spf13/hugoThemeSiteScript

This now runs fine and builds a site with all the themes.

To run it locally:

`./generateThemeSite.sh http://localhost:1313 && hugo server  -s hugoThemeSite/themeSite`

Most of the themes are now up-to-spec, but the site needs some general polishing:
- Do the necessary HTML/CSS adjustments to make it look good.
- Consider removing the left menu (put menu links in header) to let the themes get all the attention.

**Comment by bep** [comment]
@alireza-ahmadi Any status update on this?

/cc @dcorb

**Comment by alireza-ahmadi** [comment]
@bep I was too busy in the last week, but the next week is holiday in my country and I have some time to work more on this issue.

**Comment by alireza-ahmadi** [comment]
@spf13 @bep I have applied some minor tweaks on the HugoThemeSite, But I think for getting the best result, we should polish the entire **gohugo.io** website. So if you are agree, I want to redesign the Hugo website, Otherwise I will finish current tweaks without editing other parts of website. We can talk about this on [Gitter](http://gitter.im) channel.

You can see some of WIP tweaks in [this screenshot](https://dl.dropboxusercontent.com/u/99809313/thumb1.png) and [this](https://dl.dropboxusercontent.com/u/99809313/HugoPolish.webm) and [this](https://dl.dropboxusercontent.com/u/99809313/HugoMainFirstProto.webm) screencasts.

**Comment by bep** [comment]
I think it looks really nice. 

@spf13 is the decision maker here.

**Comment by spf13** [comment]
I think it looks awesome! @alireza-ahmadi Welcome aboard. 

In the spirt of getting the theme site done asap, perhaps we just make enough tweaks there to get it to a decent place, push it live, then work on the redesign.

**Comment by alireza-ahmadi** [comment]
@spf13 Well, I will finish the theme site's tweaks in the next two days and then start working on the main site redesign.

**Comment by spf13** [comment]
That sounds amazing.

**Comment by bep** [comment]
@alireza-ahmadi this will be a big seller for Hugo ... I have some functional issues on my list of TODOS, but it may be more motivational to do those with a fresh design. 

Just ping me if you have any practical questions ... I'm online ... Often.

**Comment by spf13** [comment]
I'm just finishing the biggest undertaking of my career and will be a lot more available from next week on.

**Comment by alireza-ahmadi** [comment]
After the completion of themes site's polish, We can set a meeting on Gitter and talk about new design,  Certainly your ideas can help me to improve my design.

**Comment by alireza-ahmadi** [comment]
@bep @spf13 I have pushed changes to [my fork of the repo](https://github.com/alireza-ahmadi/hugoThemesSite/), You can replace my repo URL with the default one in the generator's script and see the changes. Currently it has some bugs, But I am trying to fix them, Also I will improve the design specially on the single page. Your feedback is welcome.

**Comment by bep** [comment]
@alireza-ahmadi In general I think it is a big, big improvement. I have one suggestion to make it even cleaner: Get rid of the left menu. We should have a link back to gohugo.io somewhere, but it doesn't need a menu to say so. @spf13 agree?

If you could wrap it up in a pull request it would be splendid. There are still some issues that we have to fix, but I believe we are close.

**Comment by spf13** [comment]
@alireza-ahmadi You teased us with all the improvements to this site and the docs one. I know a lot of people are dying to see this go live. How is it going? How can we help?

**Comment by alireza-ahmadi** [comment]
@spf13 I am really sorry, I was too busy in the last month. I will try my best to complete polish of the Hugo themes sites and if for any reason the redesign process does not complete in the next week, I will inform you to assign this task to someone else.

**Comment by spf13** [comment]
No need to appologize. We are all volunteers doing this in our "free time" and completely understand. We are just excited to have you on our team and are looking forward to your contributions. 

Best,
Steve

## 

Steve Francia
http://stevefrancia.com
http://spf13.com
http://twitter.com/spf13

On Fri, May 15, 2015 at 1:19 AM -0700, "Alireza Ahmadi" notifications@github.com wrote:

@spf13 I am really sorry, I was too busy in the last month. I will try my best to complete polish of the Hugo themes sites and if for any reason the redesign process does not complete in the next week, I will inform you to assign this task to someone else.

**Comment by bep** [comment]
@alireza-ahmadi what is the status of this? I think this issue has been dragging out too long. It's better that you create a Pull Request with what you have done, we can test it, get it in a "good enough" state -- then publish it.

**Comment by alireza-ahmadi** [comment]
@bep OK, I will create a pull request in next 2 days.

**Comment by bep** [comment]
@alireza-ahmadi what is the current status on this?

**Comment by bep** [comment]
@spf13 it doesn't look like this polish thing worked out. What should we do about this site?

**Comment by alireza-ahmadi** [comment]
@bep I want to say that I am sorry for the last time, I am too busy and my changes on the themes sites are incomplete so I have nothing that fits a pull request, Maybe I should not promised to do this. Hope someone else can polish the theme site.

**Comment by dplesca** [comment]
Hi all,

I've done a little bit of work on this, using @alireza-ahmadi's work as a starting point. You can see my progress on my fork [here](https://github.com/dplesca/hugoThemesSite). Please let me know if it's alright and whatever else I can do.

**Comment by spf13** [comment]
This is super. Thanks @dplesca for jumping in and helping. Thanks @alireza-ahmadi for getting it started. This is open source at it's best. People lending a hand and helping each other. 

@dplesca can you send a PR for this work? We'd love to get something usable up even if it needs a bit more polish beyond that.

**Comment by dplesca** [comment]
I've sent a PR and merged it, I hope that's ok.

**Comment by spf13** [comment]
Yes, Thanks!

**Comment by digitalcraftsman** [comment]
Is there any way or maybe a script that integrates all available themes as content for this theme? It would be nice to see the  current state of the site with live/dummy data.

**Comment by bep** [comment]
@digitalcraftsman see https://github.com/spf13/hugoThemeSiteScript

There is an open issue that I have meant to do for some time: Figure a way to get theme-specific params into that mix; see #4 -- would be cool if someone could take on that challenge.

**Comment by digitalcraftsman** [comment]
@bep I cloned the repo and executed the shell script for the setup. Finally the scripts notes to run `hugo server -s hugoThemeSite/themeSite` in order to see the site. But all I get is this error message:

```
$ hugo server -s hugoThemeSite/themeSite
ERROR: 2015/07/07 Error parsing page meta data for heather-hugo.md
ERROR: 2015/07/07 Near line 8 (last key parsed ''): Bare keys cannot contain ':'.
ERROR: 2015/07/07 Near line 8 (last key parsed ''): Bare keys cannot contain ':'.
ERROR: 2015/07/07 Unable to locate template for shortcode 'chart' in page hugo-uno
ERROR: 2015/07/07 Unable to locate template for shortcode 'gist' in page liquorice
CRITICAL: 2015/07/07 Errors reading pages: Error:Near line 8 (last key parsed ''): Bare keys cannot contain ':'. for heather-hugo.md
```

**Comment by bep** [comment]
@digitalcraftsman the error is kind of obvious, and I will have a look. This script worked for me at some point, maybe some bad handling of missing values in the themes. Not sure.

**Comment by bep** [comment]
@digitalcraftsman see https://github.com/spf13/hugoThemeSiteScript/commit/23f153afe24b0ba6af193e17b8d8d47360ca572e I have added a "theme blacklist". The theme(s) will be removed from the blacklist once the pull request is merged. The script should work now.  

PS: You must wipe out the bad content in /hugoThemeSiteScript/hugoThemeSite/themeSite/content before you run the script again (this rm should be added to the script).

**Comment by digitalcraftsman** [comment]
@alireza-ahmadi As I saw in [this](https://dl.dropboxusercontent.com/u/99809313/HugoMainFirstProto.webm) small screencast, you are worked / have worked on a small redesign of the main page. Are you still doing so? I'm just asking for the sake of curiosity, because your design looks awesome.

**Comment by alireza-ahmadi** [comment]
@digitalcraftsman It's an honor for me that you like my design. I like to implement that design for the Hugo's main site but I am still too busy(until at least late July) and because I don't want to promise and break it again, I say that I am not working on it now. I will inform you if my time allowed me to implement that; also I would be glad if you or anyone else wants to redesign the main Hugo site based on my short screencast.

**Comment by digitalcraftsman** [comment]
Thanks for this update. But I'm not be the best option for the implementation with my rudimentary CSS skills. We'll see how it progresses.
