### ISSUE TITLE
Fix page load time

### ISSUE THREAD

**Issue by ghost** [gohugoio/hugoThemesSite#30]
Currently the Hugo Theme Site has a 60s page load time as measured by WebPageTest:

<img width="351" alt="screen shot 2017-04-25 at 8 01 31 pm" src="https://cloud.githubusercontent.com/assets/440298/25384212/1076f588-29f2-11e7-8294-47137fff0d6f.png">

While page load may not be the important metric it once was, it is still important. Here's why:

1. Theme site currently contains 165 images.
1. The 165 images represent 33966.8KB of image data.
1. Every new user visiting the theme site home page using a visual browser will attempt to download all 165 of those images.
1. Downloading 33966.8KB of images concurrently causes jank in the UI and hurts users on data-capped internet plans.
1. Browser busy indicators (the spinners) will typically spin for 60 seconds while the page loads images, even tough the user may only need or want to view a small portion of them.

<img width="904" alt="screen shot 2017-04-25 at 8 08 40 pm" src="https://cloud.githubusercontent.com/assets/440298/25384470/08de22dc-29f3-11e7-93be-0cce840e1721.png">

PR to follow to fix this issue. But I wanted to get #29 in first because as it stands the analytics for this site are not being measured effectively.

**Comment by bep** [comment]
It's live -- according to my Chrome console, the load time went down from 10s to 2,5 seconds.

**Comment by ghost** [comment]
Glad I could help.
