### ISSUE TITLE
Image placeholders

### ISSUE THREAD

**Issue by ghost** [gohugoio/hugoThemesSite#34]
In #32 we began effectively lazyloading image data to speed up the themes site. To do so we removed the `src` attribute from the image tags, which leads to the following perceived render for user agents supporting images with an unprimed cache:

<img width="942" alt="screen shot 2017-04-26 at 11 04 51 am" src="https://cloud.githubusercontent.com/assets/440298/25416497/aafaf02c-2a70-11e7-8f35-36cf6d5b80e2.png">

Because the hyperlink used for individual themes wraps an `img` tag and the image tag itself does not have an intrinsic size assigned (e.g. using width and height attributes or CSS), the click area of the surrounding anchor makes themes unclickable until the images begin to load. This effect is exacerbated when a user scrolls the page rapidly as images far outside the viewport are not preloaded using a lazy queue (possible with [lazysizes](https://github.com/aFarkas/lazysizes), but not really worth it yet).

To improve the current experience for mobile user agents and users on non-cable connections, we can leverage image placeholders, which will appear in place of theme images while theme images are being downloaded. The result of doing so will create a touch/click target the size of the thumbnail image to be loaded. To do this performantly, we can use a base64-endocoded SVG image asset showing the Hugo logo within a rectangle the size of the thumbnail being loaded.

If this is something you'd like to see please send me an SVG asset of the Hugo logo to jhabdas@gmail.com and I'll have a PR ready shortly. The work will be directly portable to the new theme site, so win-win.

**Comment by digitalcraftsman** [comment]
I like your idea to add placeholders while the image is lazy loaded. However, you should contact @spf13 directly in order to get the SVG version of the logo.

But using the Hugo logo as placeholder for each image that hasn't been fetched so far it can be a bit flashy. Hence I would rather use a gray-scaled version of the Hugo logo.

**Comment by digitalcraftsman** [comment]
Is it possible to fetch images right before they appear in the viewport of the browser? I.e. could the lazyloader  fetch images that would be visible if the users scrolls X more pixels?

**Comment by jhabdas** [comment]
@digitalcraftsman already done. IIRC lazysizes intelligently detects thrust in the scroll and begins preloading assets it expects to come into the viewport under default init settings (as currently configured). If we produce a Medium-style low-quality image placeholder for themes via the script we can really beef up UX. If I get the vectors I'll grayscale them and base 64-encode the SVG for the interim solution.

**Comment by jhabdas** [comment]
Sidebar: The lazyqueue is also possible to lazily load all images for high bandwidth connections without blocking the run loop in the browser. That was not clear in my initial statement.

**Comment by jhabdas** [comment]
Going to close this for now to help keep repo clean. If we want to implement later just let me know.

**Comment by jhabdas** [comment]
https://github.com/spf13/hugoThemes/issues/264 - optimization idea
