### ISSUE TITLE
Remove the Cloudflare cache etc.

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoThemesSite#35]
I was hoping we would have gotten rid of the deployment issue with the old and complex and not possible to administrate hosting solution by going to Netlify, but there still are issues, it seem.

Somehow Cloudflare still is in the picture:

* Hosting SSL? I see some HTTP error pages coming from Cloudflare ... 
* Caching static resources, CSS. I added some tagcloud CSS here that isn't there yet (http://themes.gohugo.io/css/style.css) so I assume it is cached somewhere ...

@spf13 @digitalcraftsman can you not just fix this one and for all? How hard can it be?

**Comment by spf13** [comment]
I can disable Cloudflare so it doesn't cache at all.
I'll do that now.

I don't think this is related to the https issues though.

**Comment by bep** [comment]
>I don't think this is related to the https issues though.

Me, neither. The HTTP 404 error page comes from Cloufdlare, but I suspect that is connected to the CDN cache ...

**Comment by bep** [comment]
This seems to be all good now, thanks!
