### ISSUE TITLE
Theme images broken

### ISSUE THREAD

**Issue by kaitlinnewson** [gohugoio/hugoThemesSite#36]
Looks like the links to the theme images are broken on the landing page
![screen shot 2017-04-26 at 8 53 01 am](https://cloud.githubusercontent.com/assets/6903515/25435411/e97c7392-2a5d-11e7-9287-e9f3255d915e.png)

**Comment by bep** [comment]
Thanks, we know -- @spf13 tried to remove some reduntant Cloudflare caches/SSL, and not without problems ...
