### ISSUE TITLE
Also display available tags on the individual tags pages

### ISSUE THREAD

**Issue by arikroc** [gohugoio/hugoThemesSite#37]
Continuation of https://github.com/spf13/hugoThemesSite/issues/28

e.g. display tag cloud on http://themes.gohugo.io/tags/minimal page so that user can navigate between tags without returning to homepage

**Comment by digitalcraftsman** [comment]
I.e.we should include the cloud tag on all taxonomy term pages as well. Perhaps we can highlight the current tag, e.g. "minimal", in the cloud with a different color.

**Comment by bep** [comment]
I agree. But noted, I think the front page _looked_ better without the tag cloud, but the usefulness is way more important than prettiness here. But _maybe_ we should test pulling the tags up in the black area in the top?

**Comment by digitalcraftsman** [comment]
> I agree. But noted, I think the front page looked better without the tag cloud, but the usefulness is way more important than prettiness here.

When Bud is redesigning the theme site as well it's likely that this issue will be fixed automatically.

But for now, I wouldn't pulling the tags in the black area. The container is fixed when scrolling and would only take unnecessary of the viewport. Alternatively, we can separate the tag cloud visually from the thumbnails, similar to the footer.

**Comment by bep** [comment]
Na, just let it be as is. It is not too distractive.

**Comment by onedrawingperday** [comment]
This old issue seems resolved. i.e. the tags are displayed in individual tag pages like: http://themes.gohugo.io/tags/minimal
