### ISSUE TITLE
Add some derived tags from theme.toml

### ISSUE THREAD

**Issue by ghost** [gohugoio/hugoThemesSite#38]
Many Hugo themes are being ported from existing open source themes created by authors on other static site generators. One rising star I've noticed is [hugo-tranquilpeak-theme](https://github.com/kakawait/hugo-tranquilpeak-theme), which is a port from Hexo.

Based on the values provided in in `theme.toml` we have the ability to generate taxonomy for themes based on whether or not they're ported or unported.

Wanted to float this as I could see it being of value for authors looking to create derivative works and looking for a quick slice of the data on where to start. It also helps identify themes with less potential licensing snafus for those extending.

Thoughts?

**Comment by ghost** [comment]
I may bring this up in the forums and am closing to help keep the repo clean.

**Comment by bep** [comment]
Reopening as I think this is a great idea. Looking at the TAG cloud, it could use some common tags, so to speak.

```
name = "Hyde"
license = "MIT"
licenselink = "https://github.com/spf13/hyde/blob/master/LICENSE.md"
description = "An elegant open source and mobile first theme"
homepage = "http://siteforthistheme.com/"
tags = ["blog", "company"]
features = ["blog", ]
min_version = 0.13

[author]
    name = "spf13"
    homepage = "http://spf13.com/"

# If porting an existing theme
[original]
    author = "mdo"
    homepage = "http://hyde.getpoole.com/"
    repo = "https://www.github.com/mdo/hyde"
```

Of the above we could generate:

* License
* Ported (i.e. if "[original]" is set)
* Min Hugo version (round it to "main release")

**Comment by ghost** [comment]
Thanks @bep. Perhaps this will help open the path to the later creation of a features taxonomy as well, helping theme authors start standardizing on the conventions used for naming features provided in their programs instead of stuffing them into the tags section.

**Comment by jhabdas** [comment]
Another possible derived tag: use of template inheritance, e.g. includes baseof.*

**Comment by jhabdas** [comment]
Inferred/derrived tag could be theme version based on SemVer. Thought of it after seeing https://github.com/spf13/hugoThemes/issues/259#issuecomment-302991829

The way Composer handles this could be mimicked so one is not required to keep a version in their theme.toml
