### ISSUE TITLE
Twitter card tags

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoThemesSite#40]
Seemed to have lost some SEO with the latest update. We kind of need the Twitter cards to look good when posting new themes in Twitter. The internal Hugo template should do? 

/cc @budparr @digitalcraftsman

**Comment by budparr** [comment]
It looks like the Twitter card data is there, except for the fields where `.Title` is required, because the themes use `name` instead of `title`.  ([template](https://github.com/spf13/hugo/blob/b6ea492b7a6325d04d44eeb00a990a3a0e29e0c0/tpl/tplimpl/template_embedded.go#L239))

We can also add our [Twitter handle](https://github.com/spf13/hugo/blob/b6ea492b7a6325d04d44eeb00a990a3a0e29e0c0/tpl/tplimpl/template_embedded.go#L242) to config

**Comment by bep** [comment]
http://themes.gohugo.io/minimo/ does not validate in 

https://cards-dev.twitter.com/validator

I'm pretty sure it did at some point. And it would be good to get it back in shape.

**Comment by digitalcraftsman** [comment]
Have a look at ae1376cfe6c70ca3581aff0fdb03b88424acafcc. You added a meta tag for the title that isn't / wasn't present in the internal template.

**Comment by bep** [comment]
OK and how does that help us getting it fixed?

**Comment by digitalcraftsman** [comment]
This way the title of the internal template would be overwritten depending on how Twitter is handling multiple occurrences of this specific meta tag.

Alternatively, we can set the title explicitly in the front matter with the `title` variable. The `title` attribute can be injected by the [build script](https://github.com/spf13/hugoThemes/blob/master/_script/generateThemeSite.sh#L149) into the front matter. The name of the theme itself can be extracted from the `theme.toml`.

**Comment by budparr** [comment]
I just looked at an older version locally, and it seems that some of the themes have title in front matter, others do not. After Dark, for instance, has a title, Castanet does not, but on the current version, After Dark doesn't either.

**Comment by bep** [comment]
I just tweeted about a theme, but this issue is still open:

https://twitter.com/GoHugoIO/status/874752601312677889

Could someone raise a hand and say "I will fix this" and not just throw out problems and expect someone else to pick up the thread. Add a conditional that checks for the name param? Default to title? And move it around and test it until Twitter is happy? Or not use the Hugo built-in Twitter template at all?

If someone feels up to the task, please assign it to yourself. Of I will have to do this instead up Hugo docs-site related stuff tomorrow.

**Comment by budparr** [comment]
I'm happy to take this on.

**Comment by bep** [comment]
Please do:

My little hack did not work: https://github.com/gohugoio/hugoThemesSite/commit/6b0890095a18154ccd1241d64e48a93c60a1590e

But the head-additions.html seems like it is prepended to head and not appended (which would be more useful).

**Comment by bep** [comment]
@budparr thinking about it, the simplest/cleanest is probably to duplicate the name into title in the build script, which I can do ... some time.

**Comment by bep** [comment]
Addendum:

I have added the `title` property to the themes' front matter. However, there was still an issue with Twitter showing the image in the "card"; I guess Twitter doesn't like schemaless URLs, so I changed it to https, which isn't perfect, but it works for Twitter (I know we should force https, but that is another discussion).

**Comment by budparr** [comment]
Thank you, @bep. Glad it's working.
