### ISSUE TITLE
Add spacing between prev/next link on theme info page

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoThemesSite#46]
Namely between the Sublime Hugo Theme and Slate

![ht](https://user-images.githubusercontent.com/7010165/27239349-d7db04d2-52d0-11e7-8094-fb3cdf025e35.png)

**Comment by budparr** [comment]
Can someone assign me to this, please?

**Comment by digitalcraftsman** [comment]
Sure

**Comment by digitalcraftsman** [comment]
I don't have permission to change assignees, labels etc and it doesn't look like that I'm a collaborator in this repo.

/cc @bep can you add Bud and me to the list of collaborators in this repo?

**Comment by bep** [comment]
My mistake, I had set the permissions to "Read" for all.

**Comment by digitalcraftsman** [comment]
Thanks

**Comment by anthonyfok** [comment]
Hi @budparr!  Any updates?  :-)

**Comment by onedrawingperday** [comment]
This issue seems resolved. There is more space between the prev/next links nowadays. See:

![image](https://user-images.githubusercontent.com/7918298/69415016-8338bb00-0d1c-11ea-8ec1-f67b8fcbbfd4.png)

**Comment by anthonyfok** [comment]
Yes, this was fixed by gohugoio/gohugoioTheme#87 (commit gohugoio/gohugoioTheme@66f4563)
as well as commit d8f7a14 here at gohugoio/hugoThemesSite.  Thanks for noticing and closing the issue here too.
