### ISSUE TITLE
Incorrect layout of theme page on mobile version

### ISSUE THREAD

**Issue by n10v** [gohugoio/hugoThemesSite#48]
As you can see, there is no space between "Download" and "Homepage":
![img_9982](https://user-images.githubusercontent.com/13235519/28588811-0d6cfbfe-717c-11e7-893a-84f41ad7fd1e.PNG)

**Comment by budparr** [comment]
Thanks for reporting, @bogem

**Comment by onedrawingperday** [comment]
I confirm the issue and I have addressed it with  34aee97 

The theme buttons will now have proper spacing around them on the Hugo Themes Site.

However this is a hotfix. 

The proper way would be to fix this directly in the [Hugo Theme](https://github.com/gohugoio/gohugoioTheme).

If this is done then please let me know and I will revert the above commit.
