### ISSUE TITLE
Add `version` metadata to `theme.toml`

### ISSUE THREAD

**Issue by gcushen** [gohugoio/hugoThemesSite#49]
How does a user know what version of a theme they are using (especially if they just downloaded Zip, no Git)? In order to update a theme, users require a method to discover which version they have installed and compare it with the theme's release notes or changelog.

I suggest that we adhere to best practices and add theme `version` metadata as a parameter in `theme.toml`.

Then rename `min_version` to `hugo_version` going forward to avoid confusion between theme version and minimum Hugo version required.

**Comment by radd2004** [comment]
I second this! As someone who develop themes for a number of frameworks and system, I usually rely on the version metadata for asset cache busting purposes. 

Just coming to hugo and can't figure how to best version CSS and javascript assets without a version-esque metadata.

**Comment by gcushen** [comment]
@bep @digitalcraftsman please can you kindly provide feedback on supporting **theme** `version` metadata in `theme.toml` for the purpose of properly **enabling users to update themes** (especially users who install themes with ZIP rather than Git) and **enabling theme developers to implement version-specific logic** as @radd2004 suggested? See my above comment for full details.

**Comment by bep** [comment]
I don't think we should do this. I don't see big value (I see some value) and it will add one more item to maintain -- which will probably be correct starting out, but then quickly forgotten. Wrong data is worse than no data. Versions should live in the version control system (Git).

**Comment by gcushen** [comment]
> Versions should live in the version control system (Git).

@bep so you are implying that all Hugo users must be experienced with Git if they wish to update a theme?

Academic (the most popular Hugo theme) has a significant number of users who are unfamiliar with Git and who report issues updating the theme as they are unsure which theme version they are currently on and thus which update instructions to follow. This is a **specific and very popular case for adding theme `version` to the official theme metadata file, `theme.toml`**. It's similar to the fact that the Hugo binary itself needs to know which version it is in order to update.

If you really think we shouldn't add **theme version** metadata to the official theme metadata file, then it would appear you are suggesting for us to create an **unofficial** theme metadata file to store the theme version for non-Git users?

**Comment by gcushen** [comment]
@bep bump

Theme version is inherently one of the most important parameters of a theme, thus should be recorded in the theme metadata file with a Hugo function to access it within the theme. Furthermore, ideally, Hugo functionality would be implemented to check for and apply theme updates. Pretty much every piece of popular software has these kind of core update features...

It might not be "cool" like the other features you are working on, but it would make Hugo more accessible and intuitive to use, particularly those users who are unfamiliar with Git.

**Comment by petzi53** [comment]
I support the idea to have a visible theme version in the files itself (e.g. in the config.toml). This is especially important 

- if someone (like me) is (still) not familiar with Git
- if someone (as all the users of R/RStudio and blogdown) are not creating the Hugo website via the "normal" Hugo procedure but with blogdown and update new theme versions with ZIP
- if someone is not always up-to-date with the latest release (because we are using these tools as a support for other work to be done and are not always interested to get into the details)

and most important

- if there are busy and active theme developer (like @gcushen) who brings every couple of month new features to us users and we sometimes have lost track which version we have installed several months ago.

So @bep maybe you could (re)think your argumentation for the huge diversity of users and approaches. I think this diversity is a good thing as it draws people from different fields in these exciting technological developments.

**Comment by petzi53** [comment]
I would like to support the idea of a visible version number in the theme.toml (or on another adequate place – I am not an expert on this).

My plea for this enhancement is the following:

- Not every user is familiar with Git
- Many users apply other methods (for instance R/RStudio/blogdown and update the theme with a ZIP file
- Sometimes there are very busy theme developer (like @gcushen) which provides new updates with new features every few months
- We ("normal") users are not constantly working on our websites and so it could be the case that we missed new versions or have lost track which version we have installed lately.

I think it is an advantage that there are a variety of methods to use a Hugo website. This brings new people into this exciting technical area.  @bep maybe you could (re)think your argumentation under the aspect of these diverse methods to use your wonderful work with Hugo?

**Comment by bep** [comment]
We recently got "theme inheritance and theme components". This opens up a whole set of new stuff that can be done with themes. And I have sketched some ideas about a simple package manager so you could just add the themes and components you want with the version you want and Hugo will take care of the dependencies.

But with that, we need to think hard about versions. It has to be designed, thought through; we cannot just add some random version number to a file and expect it to work. It has to work.

**Comment by petzi53** [comment]
Thanks for considering  this enhancement. And clear enough: You are the expert and have to decide when and how this change could be made.

**Comment by ghost** [comment]
If a user needs to know which version of a theme they're using it should clearly be listed in the documentation, changelog and, ideally, a repo badge. Adding it to the config creates a secondary file to version-align alongside the N already-built package managers in existence today.
