### ISSUE TITLE
Same themes are listed twice or more on the themes tags page

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugoThemesSite#50]
https://themes.gohugo.io/tags/

Issues:

1. All themes are listed twice (or more!).
2. The font size seems too big.

*Non-issue but an improvement suggestion: Show the theme description too, along with the title.*

![image](https://user-images.githubusercontent.com/3578197/37402746-175c203e-2763-11e8-95df-ec7a5aef4e3a.png)

**Comment by bep** [comment]
Describing the problem is better to put in the issue subject instead of a vague question.

**Comment by kaushalmodi** [comment]
~~OK, will describe it better in the subject next time.~~ (**Done**)

But I wished disabling tags wasn't the "solution". Using the `tags` page would be useful to look at tags in alphabetical order.

At the moment, the tags shown in the sidebar on https://themes.gohugo.io/ are not in alphabetical order, so having https://themes.gohugo.io/tags/ where they could be listed alphabetically would be nice.

Can this issue be reopened to fix the root cause?

**Comment by bep** [comment]
@kaushalmodi there was obviously not a template suited for displaying those tags, so disabling that view was the proper fix for _this particular issue_.

**Comment by kaushalmodi** [comment]
OK, now https://themes.gohugo.io/tags/ shows previews of just 3 themes (*Strange Case*, *Hugo Pacman Theme*, *Liquorice*).. twice each.

---

**Update:** Probably just those 3 themes are completely untagged.. but need to figure out the root issue of that duplication.

**Update 2**: https://github.com/eliasson/liquorice/issues/16, https://github.com/coderzh/hugo-pacman-theme/issues/18, https://github.com/ExchangeRate-API/strange-case/issues/6
