### ISSUE TITLE
wrong theme count

### ISSUE THREAD

**Issue by caarlos0** [gohugoio/hugoThemesSite#51]
At https://themes.gohugo.io if I look at the sidebar, it says it has 7 themes with the `docs` tag, but if I click in the link ( https://themes.gohugo.io/tags/docs/ ) it shows only 4.

This probably happens with more tags...

---

![image](https://user-images.githubusercontent.com/245435/37881893-3f7a0c2e-3074-11e8-8aa1-93b001f17488.png)

![image](https://user-images.githubusercontent.com/245435/37881896-44fcb958-3074-11e8-9f33-b1a1c85e0c05.png)

refs https://github.com/gohugoio/hugo/issues/4537

**Comment by FelicianoTech** [comment]
I built the themes website locally and the count in the sidebar shows the correct amount.

So either:

1. The site is somehow being built differently when built for production.
2. The build process/production server has left over files? Maybe stuck submodules that need to be deleted?

**Comment by bep** [comment]
I can try to build without cache to see if it helps ...

**Comment by bep** [comment]
That seems to have fixed it. I suspect this is more or less form when I refactored into bundles ... with some old stale content left. I will keep this issue open to remind me to improve the build script.

**Comment by caarlos0** [comment]
Awesome!

**Comment by digitalcraftsman** [comment]
I can't reproduce this issue either nor can it be seen on www.themes.gohugo.io.
