### ISSUE TITLE
Theme demo broken, probably because of incorrect BaseURL (minimo)

### ISSUE THREAD

**Issue by MunifTanjim** [gohugoio/hugoThemesSite#52]
The [Minimo demo](https://themes.gohugo.io/theme/minimo/) is broken.

In the [gohugoio/hugoThemes](https://github.com/gohugoio/hugoThemes) repository, Minimo is at `minimo@30e19ed`, which is the latest commit.

But in the theme's demo site, it seems like the BaseURL is set to `https://themes.gohugo.io` instead of `https://themes.gohugo.io/theme/minimo`. So, the theme can't load Javascript assets.

Either that, or it's somehow stuck with a build from an older commit.

**Comment by bep** [comment]
BaseURL is fine, see https://github.com/MunifTanjim/minimo/issues/121
