### ISSUE TITLE
Theme names on homepage are capitalized wrong

### ISSUE THREAD

**Issue by mistermantas** [gohugoio/hugoThemesSite#55]
The names in `theme.toml` are ignored and, I guess, the names of the theme directories are used instead for some reason? Why?

**Comment by bep** [comment]
>Why?

The site is built by a fairly simple bash script. And my bash skills at that time didn't allow for too much TOML parsing ... But we should be able to fix that.

**Comment by mistermantas** [comment]
I see. I’d love to see it be fixed — it’s a big pet peeve of mine. 🙂

**Comment by coliff** [comment]
Regarding the Theme tags on the sidebar; if we wanted every word to be capitalized. e.g. `Google Analytics` instead of `Google analytics` we could fix that with a bit of CSS

```
nav .link {
    text-transform: capitalize;
}
```

**Comment by mistermantas** [comment]
I don't think you get it, I ***don't*** want this behavior. It should be, as per the `theme.toml`, `cState' and not 'Cstate'. Looks ugly to my eye
