### ISSUE TITLE
Invalid header rule on the Themes website

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugoThemesSite#57]
The following is from the report of the [latest deploy](https://app.netlify.com/sites/hugothemes/deploys/5c2ff22f026856000820bc08) of the Hugo Themes website on Netlify:

---

1 out of 2 header rules could not be processed. Check your site’s /_headers file for verification. You can learn more in the docs, or test your rules in the Netlify playground.

In /_headers:

    /* */
 
---

It seems that the problem is located at: https://github.com/gohugoio/hugoThemesSite/blob/master/static/_headers#L1

Can someone more knowledgeable than me look into this?

Thanks.

**Comment by budparr** [comment]
The headers validate. https://play.netlify.com/headers but I wonder if the error is actually related to the mixed content.

**Comment by onedrawingperday** [comment]
Hello @budparr 

Yes I also noticed that the headers validate in the playground sometime after I opened this issue.

I guess we'll find out if mixed content is the culprit once https://github.com/gohugoio/hugoThemes/issues/532 is resolved.

**Comment by onedrawingperday** [comment]
> I wonder if the error is actually related to the mixed content.

@budparr 

Since https://github.com/gohugoio/hugoThemes/pull/547 was merged theme demos use the `contentDir` of the Hugo Basic Example repo.

As of yesterday according to the latest deploy log all content on the website is secure, yet somehow the invalid header error persists: https://app.netlify.com/sites/hugothemes/deploys/5c50d84fab373a0008cbfd04

**Comment by budparr** [comment]
@onedrawingperday Thank you. Actually, it's a simple typo. I seemed to have glossed over that before. 

`*/` should be `/*`
