### ISSUE TITLE
Tags selection broken on mobile

### ISSUE THREAD

**Issue by hhrutter** [gohugoio/hugoThemesSite#58]
I wanted to browse *Responsive* themes on Android or iPhone.
Both just show all tags between Modern(12) and Widget(6).

It is impossible to scroll up or down and therefore one cannot select *Responsive*
or respectively any other tags outside of the range mentioned above.

**Comment by onedrawingperday** [comment]
This is due to the CSS of the theme used on the Theme Site.

The theme has its own repo and I am closing this issue in favor of https://github.com/gohugoio/gohugoioTheme/issues/141

Feel free to continue the discussion there.
