### ISSUE TITLE
History navigation keyboard shortcut triggers theme navigation

### ISSUE THREAD

**Issue by QuLogic** [gohugoio/hugoThemesSite#59]
Say you're on a theme page with some external links (e.g., [hugo-theme-terminal](https://themes.gohugo.io/hugo-theme-terminal/)) and click one of those links. You are now on an external site. To go back, you use the keyboard shortcut <kbd>Alt+Left</kbd>. This takes you back to the theme page, but it _also_ triggers the theme navigation that's bound to <kbd>Left</kbd>. So you then end up on the previous theme.

This is on Firefox 66.0.1.

**Comment by onedrawingperday** [comment]
Cannot reproduce in Firefox 70.0.1
