### ISSUE TITLE
Change navbar link for Hugo Themes Showcase

### ISSUE THREAD

**Issue by darshanbaral** [gohugoio/hugoThemesSite#60]
Maybe it would be better to change the link [here](https://github.com/gohugoio/hugoThemesSite/blob/5f67673b33526823a3a03c671fb62a9a5b59d59e/config.toml#L109) from https://github.com/gohugoio/hugo to https://github.com/gohugoio/hugoThemes

**Comment by digitalcraftsman** [comment]
Hello Darshan,

as far is I can tell the menu was designed as a global menu, meaning that the links are the same on every page. This implies that the menu is independent of its context. In the context of the Hugo theme showcase it makes sense to link to the corresponding GitHub repo. On the other hand it breaks the global consistency of the menu and lead users to false assumptions about the destination of the link.

At the end we have to weigh up global consistency against a context dependency which may lead to false assumptions. Personally, I prefer global consistency, but this are just my 2 cents.

**Comment by darshanbaral** [comment]
Should the circled element link to https://gohugo.io/ instead of https://themes.gohugo.io/ in the [Theme Site](https://themes.gohugo.io/). I'm guessing the `baseurl` has to be changed [here](https://github.com/gohugoio/hugoThemesSite/blob/5f67673b33526823a3a03c671fb62a9a5b59d59e/config.toml#L1).

![image](https://user-images.githubusercontent.com/10451486/57327847-b9865400-70c4-11e9-81c5-a90726fbbe26.png)

**Comment by darshanbaral** [comment]
Duplicate of https://github.com/gohugoio/hugoDocs/issues/758.
