### ISSUE TITLE
Double slashes on demo site for each theme

### ISSUE THREAD

**Issue by VincentTam** [gohugoio/hugoThemesSite#62]
Steps to reproduce:

1. Open any theme.
2. Click on "demo" button.
3. Observe the error in the URL of the demo page.

Screenshot:

![Screenshot from 2019-08-06 15-19-48](https://user-images.githubusercontent.com/5748535/62543194-a454c900-b85d-11e9-8bbd-85c882bce43b.png)

**Comment by onedrawingperday** [comment]
This issue  no longer seems present. I cannot reproduce.
