### ISSUE TITLE
Preview <img> is larger than image on higher resolutions

### ISSUE THREAD

**Issue by pacollins** [gohugoio/hugoThemesSite#63]
Originally posted at gohugoio/hugoThemes#695.

<img width="339" alt="Screen Shot 2019-08-23 at 9 38 07 AM" src="https://user-images.githubusercontent.com/11359433/63596689-c94d7980-c589-11e9-88c0-51ecfd05c219.png">

That is what is happening. It gets larger as the screen gets wider.

**Comment by onedrawingperday** [comment]
I confirm this bug and I will look into it in the coming days.

**Comment by onedrawingperday** [comment]
Commit 0c477f6 has fixed this issue on my end @pacollins 

https://themes.gohugo.io/

Let me know if the issue remains on your end.
