### ISSUE TITLE
Add stale bot in this repo

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugoThemesSite#66]
The issue tracker of this repo is cluttered with inactive issues opened years ago.

~~So I will add~~ [stale](https://github.com/marketplace/stale) to have these issues removed after a period of time.

Turns out that I cannot add stale since I am not an admin of this repo.

So @bep if you can please enable [stale](https://github.com/marketplace/stale) in this repo and then I will sort its settings and add a `keep` tag to issues that need to be kept active.

**Comment by bep** [comment]
Done.
