### ISSUE TITLE
Question about Goldmark settings

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugoThemesSite#67]
@bep 

I have been testing Hugo Themes with Goldmark and I have noticed that if a theme has a link in its README like so: 

`[Live Demo here!](https://<some-url>/)`

Then the link is output as above i.e. (it does not become `Live Demo here!`).

In the [config](https://github.com/gohugoio/hugoThemesSite/blob/master/config.toml) of the ThemesSite should we enter the `unsafe` parameter for Goldmark or not?

**Comment by bep** [comment]
>In the config of the ThemesSite should we enter the unsafe parameter for Goldmark or not?

No.

**Comment by bep** [comment]
>In the config of the ThemesSite should we enter the unsafe parameter for Goldmark or not?

No. 

If there are issues we fix them in some other way. If that means that we for some period run with Blackfriday, fine.

As to the above, I get:

```html
[Google Search!](<a href="https://google.com/">https://google.com/</a>)
```

Which is making a workable link, it is not "output as above". Which  is not a blocker for the theme site, but I will raise an issue on Goldmark. I don't see how the above conforms with the CommonMark spec.

**Comment by bep** [comment]
See https://github.com/yuin/goldmark/issues/34

**Comment by bep** [comment]
This is now fixed.
