### ISSUE TITLE
The `.git` directory is extremely bloated

### ISSUE THREAD

**Issue by queensferryme** [gohugoio/hugoThemesSite#73]
I have been following the [directions](https://github.com/gohugoio/hugoThemes#testing-a-theme-with-the-hugo-themes-website-build-script) from [gohugoio/hugoThemes](https://github.com/gohugoio/hugoThemes) to test my [theme](https://github.com/queensferryme/hugo-theme-texify).  

Runing the `reviewTheme.sh` script will clone this repo, and it takes extremely long time (due to slow network connections) to finish. After some investigation I found that the `.git` directory is **100+Mb** in size while all other useful source codes combined are less than 20Kb.

The `.git` directory is bloated and I hope something could be done to reduce its size, or replace the clone with downloading zip in the `reviewTheme.sh` script.

**Comment by hugo-sid** [comment]
@bep, I think this issue can be closed since it relates to the old themes website.
