### ISSUE TITLE
Cupper Theme in Hugo not working

### ISSUE THREAD

**Issue by pm-bhatt** [gohugoio/hugoThemesSite#74]
I tried to use Cupper theme in Hugo site. It does not work

Gives below error :  **_themes/cupper-hugo-theme-master/layouts/partials/head.html:14:1": parse failed: template: partials/head.html:14: unclosed action_**

**Comment by pm-bhatt** [comment]
I am using Ubuntu 20.10 LTS as WSL. Other themes are working fine but the problem is with this theme only

**Comment by coliff** [comment]
Is it this one: https://github.com/zwbetz-gh/cupper-hugo-theme ?
If so, I think it'd be worthwhile opening an issue there.

**Comment by pm-bhatt** [comment]
Hi @coliff: Yes this is the theme. And I will surely report the issue there.

Apology from my end, I am new to Github and learning how to contribute
